/* Linkora Solutions attendance portal. All attendance mutations use secure database RPCs. */
(() => {
  const $ = (s) => document.querySelector(s);
  const app = $('#app');
  const sb = window.supabase.createClient('https://nbvylffxmjmovyfhbytu.supabase.co', 'sb_publishable_5qYFSQZctSIVupj5_nGg3g_v_E5fVNA');
  const state = { user: null, profile: null, employees: [], attendance: [], leaves: [], settings: null, view: 'dashboard' };
  const esc = (v='') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const isAdmin = () => state.profile?.role === 'admin';
  const tz = () => state.settings?.timezone || 'Asia/Karachi';
  const day = () => new Intl.DateTimeFormat('en-CA', {timeZone:tz()}).format(new Date());
  const date = (value) => value ? new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:tz()}).format(new Date(value+'T12:00:00')) : '—';
  const time = (value) => value ? new Intl.DateTimeFormat('en-US',{hour:'2-digit',minute:'2-digit',timeZone:tz()}).format(new Date(value)) : '—';
  const hours = (r) => r?.working_minutes != null ? `${Math.floor(r.working_minutes / 60)}h ${r.working_minutes % 60}m` : '—';
  const notify = (message, kind='success') => { const n=document.createElement('div'); n.className=`toast ${kind}`; n.textContent=message; $('#toast-region').append(n); setTimeout(()=>n.remove(),4200); };
  const fail = (error, fallback='Unable to complete the request.') => notify(error?.message || fallback, 'error');
  const setBusy = (button, busy, label) => { button.disabled=busy; button.dataset.label ||= button.textContent; button.textContent=busy ? label : button.dataset.label; };

  async function load() {
    const {data:{user}} = await sb.auth.getUser(); state.user=user;
    if (!user) return false;
    const {data:profile,error} = await sb.from('profiles').select('*').eq('id', user.id).single();
    if (error || !profile || !profile.active) { await sb.auth.signOut(); throw new Error('Your account is inactive or has not been configured.'); }
    state.profile=profile;
    const [settings, employees, attendance, leaves] = await Promise.all([
      sb.from('company_settings').select('*').single(),
      isAdmin() ? sb.from('profiles').select('*').order('full_name') : Promise.resolve({data:[profile]}),
      sb.from('attendance_records').select('*').order('attendance_date',{ascending:false}),
      sb.from('leave_requests').select('*').order('start_date',{ascending:false})
    ]);
    if (settings.error || attendance.error || leaves.error) throw new Error('Unable to load portal data. Please refresh or contact your administrator.');
    state.settings=settings.data; state.employees=employees.data || [profile]; state.attendance=attendance.data || []; state.leaves=leaves.data || [];
    return true;
  }
  const employee = (id) => state.employees.find(x=>x.id===id);
  const todayRecord = () => state.attendance.find(x=>x.employee_id===state.user.id && x.attendance_date===day());
  const badge = (status) => `<span class="badge ${String(status).toLowerCase().replace(/\\s/g,'')}">${esc(status)}</span>`;
  const table = (rows, admin=false) => rows.length ? `<table><thead><tr>${admin?'<th>Employee</th><th>Department</th>':''}<th>Date</th><th>Check in</th><th>Check out</th><th>Working hours</th><th>Status</th>${admin?'<th>Action</th>':''}</tr></thead><tbody>${rows.map(r=>`<tr>${admin?`<td class="employee-name">${esc(employee(r.employee_id)?.full_name || 'Unknown')}<small>${esc(employee(r.employee_id)?.employee_id || '')}</small></td><td>${esc(employee(r.employee_id)?.department || '—')}</td>`:''}<td>${date(r.attendance_date)}</td><td>${time(r.check_in)}</td><td>${time(r.check_out)}</td><td>${hours(r)}</td><td>${badge(r.status)}</td>${admin?`<td><button class="action-link" data-correct="${r.id}">Correct</button></td>`:''}</tr>`).join('')}</tbody></table>` : '<div class="empty">No attendance records found for the selected criteria.</div>';

  function login() {
    app.innerHTML=`<div class="login-page"><section class="login-hero"><div class="wordmark">LINKORA <b>SOLUTIONS</b></div><div><h1>A clearer view of every workday.</h1><p>Secure attendance, time off, and workforce management for your Linkora team.</p></div><div class="secure-note">◈ Your attendance records are protected by role-based access.</div></section><section class="login-panel"><div class="login-card"><a class="back-link" href="index.html">← Back to website</a><h2>Welcome back</h2><p>Sign in with credentials assigned by your administrator.</p><form id="loginForm"><div class="field"><label>EMPLOYEE ID OR EMAIL</label><input name="identity" autocomplete="username" required placeholder="e.g. EMP-001 or you@company.com"></div><div class="field"><label>PASSWORD</label><input name="password" type="password" autocomplete="current-password" required></div><button class="primary-btn">Sign in securely →</button></form><div class="demo-login">Need access? Contact your Linkora Solutions administrator. Credentials are never stored in this website.</div></div></section></div>`;
    $('#loginForm').onsubmit=async e=>{ e.preventDefault(); const f=new FormData(e.target), button=e.target.querySelector('button'); let email=String(f.get('identity')).trim();
      try { setBusy(button,true,'Signing in…'); if(!email.includes('@')) { const {data,error}=await sb.rpc('employee_login_email',{lookup_employee_id:email}); if(error || !data) throw new Error('Employee ID was not found or the account is inactive.'); email=data; }
        const {error}=await sb.auth.signInWithPassword({email,password:f.get('password')}); if(error) throw error; await load(); render();
      } catch(error) { fail(error,'Unable to sign in.'); setBusy(button,false); } };
  }
  function sidebar() { const admin=isAdmin(); return `<aside class="sidebar" id="sidebar"><div class="wordmark">LINKORA <b>SOLUTIONS</b></div><div class="nav-label">${admin?'MANAGEMENT':'MY WORKSPACE'}</div><nav class="side-nav"><button data-view="dashboard">▦ &nbsp; Dashboard</button>${admin?'<button data-view="employees">♙ &nbsp; Employees</button><button data-view="attendance">◷ &nbsp; Attendance</button><button data-view="leaves">◫ &nbsp; Leave management</button><button data-view="reports">◔ &nbsp; Reports</button><button data-view="settings">⚙ &nbsp; Settings</button>':'<button data-view="attendance">◷ &nbsp; My attendance</button><button data-view="leaves">◫ &nbsp; Leave / time off</button><button data-view="profile">♙ &nbsp; My profile</button>'}</nav><div class="sidebar-bottom">Signed in as<br><b>${esc(state.profile.full_name)}</b><br><button class="signout" id="signout">↪ Sign out</button></div></aside>`; }
  function shell(title, description, content) { app.innerHTML=`<div class="portal">${sidebar()}<div class="content"><header class="topbar"><div class="page-title"><button class="mobile-menu" id="menu">☰</button><h1>${title}</h1><p>${description}</p></div><div class="user-chip"><div class="avatar">${esc(state.profile.full_name.split(' ').map(x=>x[0]).slice(0,2).join(''))}</div><div>${esc(state.profile.full_name)}<br><small>${esc(state.profile.designation || state.profile.role)}</small></div></div></header><main class="page">${content}</main></div></div>`;
    document.querySelectorAll('[data-view]').forEach(b=>{ b.classList.toggle('active',b.dataset.view===state.view); b.onclick=()=>{state.view=b.dataset.view; render();};}); $('#signout').onclick=async()=>{await sb.auth.signOut(); state.user=null; state.profile=null; login();}; $('#menu').onclick=()=>$('#sidebar').classList.toggle('open');
  }
  function employeeDashboard() { const r=todayRecord(); const recent=state.attendance.slice(0,5); const message=r?.check_out?'Workday completed':r?.check_in?'Currently working':'Not checked in'; shell(`Good day, ${esc(state.profile.full_name.split(' ')[0])}`, 'Your workday at a glance.', `<div class="overview-grid"><section class="card status-card"><div><div class="subtle"><i class="status-dot"></i> ${message}</div><h2>${r?.check_out?'Great work today.':r?.check_in?'Your workday is in progress.':'Ready when you are.'}</h2><div class="subtle">${r?.check_in?`Checked in at ${time(r.check_in)}`:'Start work when you are ready.'}</div><div class="attendance-actions"><button class="primary-btn" id="checkin" ${r?'disabled':''}>Check in</button><button class="secondary-btn" id="checkout" ${!r?.check_in||r?.check_out?'disabled':''}>Check out</button></div></div><div><div class="time-display" id="clock"></div><div class="time-date">${date(day())}</div></div></section><section class="card"><div class="summary-head"><h2>Today’s summary</h2><span class="month-title">${tz()}</span></div><div class="summary-bars"><div class="bar-line"><span>Check in</span><div class="bar"><i style="width:100%"></i></div><b>${time(r?.check_in)}</b></div><div class="bar-line"><span>Check out</span><div class="bar"><i style="width:100%;background:#4475e8"></i></div><b>${time(r?.check_out)}</b></div><div class="bar-line"><span>Worked</span><div class="bar"><i style="width:70%;background:#e79a24"></i></div><b>${hours(r)}</b></div></div></section></div><section class="card table-card section-gap"><div class="table-head"><h2>Recent attendance</h2><button class="action-link" data-view="attendance">View all →</button></div>${table(recent)}</section>`);
    $('#checkin').onclick=()=>attendanceAction('check_in',$('#checkin'),'Checking in…','Check-in recorded successfully.'); $('#checkout').onclick=()=>attendanceAction('check_out',$('#checkout'),'Checking out…','Check-out completed successfully.'); clock();
  }
  async function attendanceAction(action, button, label, success) { try { setBusy(button,true,label); const {error}=await sb.rpc(action); if(error) throw error; await load(); notify(success); render(); } catch(error) { fail(error); setBusy(button,false); } }
  function adminDashboard() { const records=state.attendance.filter(r=>r.attendance_date===day()); const employeeCount=state.employees.filter(x=>x.role==='employee'&&x.active).length; const leave=state.leaves.filter(l=>l.status==='Approved'&&day()>=l.start_date&&day()<=l.end_date).length; const avg=records.filter(r=>r.working_minutes!=null); const average=avg.length?Math.round(avg.reduce((n,r)=>n+r.working_minutes,0)/avg.length):0;
    shell('Attendance dashboard','Live overview powered by your workforce data.', `<div class="stats-grid"><section class="card stat-card"><div class="stat-icon">♙</div><p>TOTAL EMPLOYEES</p><strong>${employeeCount}</strong></section><section class="card stat-card"><div class="stat-icon">✓</div><p>PRESENT TODAY</p><strong>${records.length}</strong></section><section class="card stat-card"><div class="stat-icon">◷</div><p>CURRENTLY WORKING</p><strong>${records.filter(r=>r.check_in&&!r.check_out).length}</strong></section><section class="card stat-card"><div class="stat-icon">◫</div><p>ON LEAVE</p><strong>${leave}</strong></section><section class="card stat-card"><div class="stat-icon">◔</div><p>AVERAGE HOURS</p><strong>${hours({working_minutes:average})}</strong></section></div><section class="card table-card section-gap"><div class="table-head"><h2>Today's attendance</h2><button class="action-link" data-view="attendance">View all →</button></div>${table(records,true)}</section>`);
  }
  function attendance() { const admin=isAdmin(); const rows=state.attendance; shell(admin?'Attendance history':'My attendance history',admin?'Search and review secure attendance records.':'Review your check-in and check-out history.', `<section class="card table-card"><div class="table-head"><h2>Attendance records</h2><div class="filters"><input id="search" class="filter" placeholder="Search employee"><input id="dateFilter" class="filter" type="date"><select id="statusFilter" class="filter"><option value="">All statuses</option><option>Working</option><option>Completed</option><option>Late</option></select>${admin?'<button class="secondary-btn" id="export">Export CSV</button>':''}</div></div><div id="records"></div></section>`);
    const draw=()=>{const query=$('#search').value.toLowerCase(), d=$('#dateFilter').value, s=$('#statusFilter').value; const filtered=rows.filter(r=>{const p=employee(r.employee_id)||state.profile; return (!d||r.attendance_date===d)&&(!s||r.status===s)&&(!query||`${p.full_name} ${p.employee_id} ${p.email}`.toLowerCase().includes(query));}); $('#records').innerHTML=table(filtered,admin); if(admin) document.querySelectorAll('[data-correct]').forEach(b=>b.onclick=()=>correctionModal(state.attendance.find(r=>r.id===b.dataset.correct))); return filtered;}; ['search','dateFilter','statusFilter'].forEach(id=>$('#'+id).oninput=draw); $('#statusFilter').onchange=draw; draw();
    if ($('#export')) $('#export').onclick=()=>{const data=draw(); const lines=['Employee ID,Employee,Date,Check In,Check Out,Working Minutes,Status',...data.map(r=>[employee(r.employee_id)?.employee_id,employee(r.employee_id)?.full_name,r.attendance_date,r.check_in||'',r.check_out||'',r.working_minutes||'',r.status].map(v=>JSON.stringify(v??'')).join(','))]; const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([lines.join('\\n')],{type:'text/csv'})); a.download=`linkora-attendance-${day()}.csv`; a.click(); URL.revokeObjectURL(a.href); notify('Attendance report exported.');};
  }
  function leaves() { const admin=isAdmin(), rows=state.leaves; shell(admin?'Leave management':'Leave / time off',admin?'Review and approve employee leave requests.':'Submit and track your leave requests.', `<div class="leave-grid">${!admin?`<section class="card form-card"><h2>Request time off</h2><form id="leaveForm"><div class="field"><label>LEAVE TYPE</label><select name="leave_type"><option>Casual Leave</option><option>Sick Leave</option><option>Annual Leave</option><option>Emergency Leave</option><option>Unpaid Leave</option><option>Other</option></select></div><div class="form-row"><div class="field"><label>START DATE</label><input required type="date" name="start_date" min="${day()}"></div><div class="field"><label>END DATE</label><input required type="date" name="end_date" min="${day()}"></div></div><div class="field"><label>REASON</label><textarea required name="reason"></textarea></div><div class="form-actions"><button class="primary-btn">Submit request</button></div></form></section>`:''}<section class="card table-card"><div class="table-head"><h2>${admin?'All requests':'My requests'}</h2></div><table><thead><tr>${admin?'<th>Employee</th>':''}<th>Type</th><th>Dates</th><th>Reason</th><th>Status</th>${admin?'<th>Action</th>':''}</tr></thead><tbody>${rows.map(l=>`<tr>${admin?`<td>${esc(employee(l.employee_id)?.full_name || '')}</td>`:''}<td>${esc(l.leave_type)}</td><td>${date(l.start_date)} – ${date(l.end_date)}</td><td>${esc(l.reason)}</td><td>${badge(l.status)}</td>${admin?`<td>${l.status==='Pending'?`<button class="action-link" data-leave="${l.id}" data-status="Approved">Approve</button> <button class="action-link" data-leave="${l.id}" data-status="Rejected">Reject</button>`:'—'}</td>`:''}</tr>`).join('') || '<tr><td colspan="6" class="empty">No leave records available.</td></tr>'}</tbody></table></section></div>`);
    if(!admin) $('#leaveForm').onsubmit=async e=>{e.preventDefault(); const d=Object.fromEntries(new FormData(e.target)); if(d.end_date<d.start_date)return notify('End date cannot be before start date.','error'); const b=e.target.querySelector('button'); try{setBusy(b,true,'Saving…'); const {error}=await sb.from('leave_requests').insert({...d,employee_id:state.user.id});if(error)throw error;await load();notify('Leave request submitted successfully.');render();}catch(error){fail(error);setBusy(b,false);}};
    else document.querySelectorAll('[data-leave]').forEach(b=>b.onclick=async()=>{try{const {error}=await sb.from('leave_requests').update({status:b.dataset.status}).eq('id',b.dataset.leave);if(error)throw error;await load();notify(`Leave request ${b.dataset.status.toLowerCase()}.`);render();}catch(error){fail(error);}});
  }
  function employees() { shell('Employee directory','Create, search, and manage employee accounts.', `<section class="card table-card"><div class="table-head"><h2>All employees</h2><div class="admin-tools"><input id="employeeSearch" class="filter" placeholder="Search employees"><button class="primary-btn" id="addEmployee">+ Add employee</button></div></div><div id="employees"></div></section>`); const draw=()=>{const q=$('#employeeSearch').value.toLowerCase();const rows=state.employees.filter(e=>e.role==='employee'&&`${e.full_name} ${e.employee_id} ${e.email} ${e.department}`.toLowerCase().includes(q));$('#employees').innerHTML=rows.length?`<table><thead><tr><th>Employee</th><th>Department</th><th>Designation</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.map(e=>`<tr><td class="employee-name">${esc(e.full_name)}<small>${esc(e.employee_id)} · ${esc(e.email)}</small></td><td>${esc(e.department||'—')}</td><td>${esc(e.designation||'—')}</td><td>${badge(e.active?'Active':'Inactive')}</td><td><button class="action-link" data-edit="${e.id}">Edit</button> <button class="action-link" data-reset="${e.id}">Reset password</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">No employees found.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>employeeModal(employee(b.dataset.edit)));document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>passwordModal(b.dataset.reset));};$('#employeeSearch').oninput=draw;$('#addEmployee').onclick=()=>employeeModal();draw(); }
  function employeeModal(current=null) { document.body.insertAdjacentHTML('beforeend',`<div class="modal-wrap" id="modal"><form class="modal" id="employeeForm"><div class="modal-head"><h2>${current?'Edit employee':'Add employee'}</h2><button type="button" class="close">×</button></div><div class="form-row"><div class="field"><label>FULL NAME</label><input required name="name" value="${esc(current?.full_name||'')}"></div><div class="field"><label>EMPLOYEE ID</label><input required name="employeeId" value="${esc(current?.employee_id||'')}"></div></div><div class="field"><label>WORK EMAIL</label><input required type="email" name="email" value="${esc(current?.email||'')}"></div><div class="form-row"><div class="field"><label>DEPARTMENT</label><input required name="department" value="${esc(current?.department||'')}"></div><div class="field"><label>DESIGNATION</label><input required name="designation" value="${esc(current?.designation||'')}"></div></div><div class="form-row"><div class="field"><label>PHONE</label><input name="phone" value="${esc(current?.phone||'')}"></div><div class="field"><label>JOINING DATE</label><input required type="date" name="joiningDate" value="${current?.joining_date||day()}"></div></div><div class="field"><label>${current?'ACCOUNT STATUS':'TEMPORARY PASSWORD'}</label>${current?`<select name="active"><option value="true" ${current.active?'selected':''}>Active</option><option value="false" ${!current.active?'selected':''}>Inactive</option></select>`:'<input required minlength="8" type="password" name="password">'} </div><div class="form-actions"><button class="primary-btn">${current?'Save changes':'Create account'}</button></div></form></div>`);$('#modal .close').onclick=()=>$('#modal').remove();$('#employeeForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));try{const {data,error}=await sb.functions.invoke('manage-employee',{body:{action:current?'update':'create',userId:current?.id,employee:{...f,active:f.active!=='false'},password:f.password}});if(error||data?.error)throw new Error(data?.error||error.message);$('#modal').remove();await load();notify(current?'Employee updated successfully.':'Employee account created successfully.');render();}catch(error){fail(error,'Employee service is unavailable. Confirm the manage-employee function is deployed.');}}; }
  function passwordModal(id) { const password=prompt('Enter a new temporary password (at least 8 characters):');if(!password)return;sb.functions.invoke('manage-employee',{body:{action:'reset-password',userId:id,password}}).then(({data,error})=>{if(error||data?.error)throw new Error(data?.error||error.message);notify('Password reset successfully.');}).catch(fail); }
  function correctionModal(record) { if(!record)return; const local=(v)=>v?new Date(v).toISOString().slice(0,16):''; document.body.insertAdjacentHTML('beforeend',`<div class="modal-wrap" id="modal"><form class="modal" id="correctionForm"><div class="modal-head"><h2>Correct attendance</h2><button type="button" class="close">×</button></div><p class="subtle">This correction is permanently attributed to your administrator account.</p><div class="field"><label>CHECK IN</label><input required type="datetime-local" name="checkIn" value="${local(record.check_in)}"></div><div class="field"><label>CHECK OUT</label><input type="datetime-local" name="checkOut" value="${local(record.check_out)}"></div><div class="field"><label>STATUS</label><select name="status"><option ${record.status==='Working'?'selected':''}>Working</option><option ${record.status==='Completed'?'selected':''}>Completed</option><option ${record.status==='Late'?'selected':''}>Late</option><option ${record.status==='Half Day'?'selected':''}>Half Day</option></select></div><div class="form-actions"><button class="primary-btn">Save correction</button></div></form></div>`);$('#modal .close').onclick=()=>$('#modal').remove();$('#correctionForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{const{error}=await sb.rpc('correct_attendance',{record_id:record.id,corrected_check_in:new Date(d.checkIn).toISOString(),corrected_check_out:d.checkOut?new Date(d.checkOut).toISOString():null,corrected_status:d.status});if(error)throw error;$('#modal').remove();await load();notify('Attendance correction saved and logged.');render();}catch(error){fail(error);}}; }
  function reports() { const completed=state.attendance.filter(r=>r.working_minutes!=null); const total=completed.reduce((n,r)=>n+r.working_minutes,0); shell('Reports','Export real attendance data for your selected records.', `<section class="card"><div class="section-title"><h2>Organization summary</h2><button class="secondary-btn" id="downloadReport">Export CSV</button></div><div class="today-details"><div class="mini-stat"><span>RECORDS</span><strong>${state.attendance.length}</strong></div><div class="mini-stat"><span>COMPLETED DAYS</span><strong>${completed.length}</strong></div><div class="mini-stat"><span>TOTAL WORKING HOURS</span><strong>${Math.floor(total/60)}h ${total%60}m</strong></div></div></section>`);$('#downloadReport').onclick=()=>{state.view='attendance';render();setTimeout(()=>$('#export').click(),0);}; }
  function settings() { const s=state.settings; shell('Settings','Configure company-wide attendance rules.', `<section class="card form-card"><h2>Company settings</h2><form id="settingsForm"><div class="form-row"><div class="field"><label>COMPANY NAME</label><input name="company_name" required value="${esc(s.company_name)}"></div><div class="field"><label>TIMEZONE</label><input name="timezone" required value="${esc(s.timezone)}"></div></div><div class="form-row"><div class="field"><label>WORKDAY START</label><input name="workday_start" required type="time" value="${s.workday_start.slice(0,5)}"></div><div class="field"><label>LATE THRESHOLD (MINUTES)</label><input name="late_after_minutes" required type="number" min="0" max="240" value="${s.late_after_minutes}"></div></div><div class="form-actions"><button class="primary-btn">Save settings</button></div></form></section>`);$('#settingsForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');try{setBusy(b,true,'Saving…');const d=Object.fromEntries(new FormData(e.target));const{error}=await sb.from('company_settings').update(d).eq('id',true);if(error)throw error;await load();notify('Settings saved successfully.');render();}catch(error){fail(error);setBusy(b,false);}}; }
  function profile() { const p=state.profile; shell('My profile','Your administrator manages your work identity.',`<div class="profile-grid"><section class="card profile-hero"><div class="profile-avatar">${esc(p.full_name.split(' ').map(x=>x[0]).join(''))}</div><h2>${esc(p.full_name)}</h2><p>${esc(p.designation||'Employee')}</p><div class="profile-list"><div><span>Employee ID</span><strong>${esc(p.employee_id)}</strong></div><div><span>Department</span><strong>${esc(p.department||'—')}</strong></div><div><span>Joining date</span><strong>${date(p.joining_date)}</strong></div></div></section><section class="card form-card"><h2>Account details</h2><p class="subtle">Contact your administrator to update protected employment information.</p><div class="profile-list"><div><span>WORK EMAIL</span><strong>${esc(p.email)}</strong></div><div><span>ACCOUNT STATUS</span><strong>${p.active?'Active':'Inactive'}</strong></div><div><span>PHONE</span><strong>${esc(p.phone||'—')}</strong></div></div></section></div>`); }
  function clock(){const update=()=>{const e=$('#clock');if(e)e.textContent=new Intl.DateTimeFormat('en-US',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:tz()}).format(new Date());};update();clearInterval(window.linkoraClock);window.linkoraClock=setInterval(update,1000);}
  function render(){const views=isAdmin()?{dashboard:adminDashboard,employees,attendance,leaves,reports,settings}:{dashboard:employeeDashboard,attendance,leaves,profile};(views[state.view]||views.dashboard)();}
  sb.auth.onAuthStateChange(async (event)=>{if(event==='SIGNED_OUT'){state.user=null;state.profile=null;login();}});
  (async()=>{try{if(await load())render();else login();}catch(error){login();notify(error.message,'error');}})();
})();
