import {createRecordingHandler,cleanup} from '../supabase/functions/workforce-recordings/handler.ts';
import type {Service} from '../supabase/functions/_shared/attendance-sync.ts';
const equal=(a:unknown,b:unknown)=>{if(a!==b)throw new Error('Assertion failed: '+a+' !== '+b)};
const user='11111111-1111-4111-8111-111111111111',session='22222222-2222-4222-8222-222222222222';
const jwt='test.'+btoa(JSON.stringify({session_id:session}))+'.verified-by-mock';
function fixture(error:unknown=null){const calls:Array<{name:string;args:Record<string,unknown>}>=[],signed:Array<unknown>=[],removed:Array<unknown>=[];
 const service={auth:{async getUser(t:string){return{data:{user:t===jwt?{id:user}:null},error:t===jwt?null:'invalid'}}},async rpc(name:string,args:Record<string,unknown>){calls.push({name,args});return{data:{path:'server/segment.webm',ttl:300,rows:[],active:true,presence:{active:true}},error}},storage:{from(bucket:string){return{async createSignedUrl(path:string,ttl:number){signed.push({bucket,path,ttl});return{data:{signedUrl:'https://private.invalid/temporary'},error:null}},async remove(paths:unknown){removed.push(paths);return{error:null}}}}}} as unknown as Service;
 const handle=createRecordingHandler(service);return{service,calls,signed,removed,handle};}
const req=(body:unknown,t=jwt,origin='https://linkorasolution.com')=>new Request('https://test.invalid',{method:'POST',headers:{Origin:origin,Authorization:'Bearer '+t},body:JSON.stringify(body)});
Deno.test('recordings deny missing/forged identity and foreign origins before privileged access',async()=>{const f=fixture();equal((await f.handle(req({action:'list'},'invalid'))).status,401);equal((await f.handle(req({action:'list'},jwt,'https://foreign.invalid'))).status,403);equal(f.calls.length,0)});
Deno.test('recordings use verified Auth identity; no client can substitute actor/session',async()=>{const f=fixture();equal((await f.handle(req({action:'list',userId:'spoof',authSession:'spoof',role:'Co-CEO'}))).status,200);equal(f.calls[0].args.p_user_id,user);equal(f.calls[0].args.p_auth_session,session)});
Deno.test('playback requires fresh database authorization before signing private URL',async()=>{const f=fixture({code:'42501'});equal((await f.handle(req({action:'playback',path:'forged'}))).status,403);equal(f.signed.length,0);const ok=fixture();const r=await ok.handle(req({action:'playback',path:'forged',ttl:999999}));equal(r.status,200);equal(r.headers.get('Cache-Control'),'no-store');equal(JSON.stringify(ok.signed),JSON.stringify([{bucket:'employee-screen-recordings',path:'server/segment.webm',ttl:300}]))});
Deno.test('begin supplies server-generated scoped close capability, never browser hash',async()=>{const f=fixture();const r=await f.handle(req({action:'begin',closeTokenHash:'spoof'}));const d=await r.json();equal(d.presence.closeToken.length,72);const p=f.calls[0].args.p_payload as Record<string,unknown>;equal(String(p.closeTokenHash).length,64);equal(p.closeTokenHash==='spoof',false);equal(p.closeTokenHash===d.presence.closeToken,false)});
Deno.test('invalid actions/bounds/error statuses safe; maintenance token independently verified',async()=>{const f=fixture({code:'54000'});equal((await f.handle(req({action:'reserve'}))).status,429);equal((await f.handle(req({action:'remote-capture'}))).status,400);equal((await f.handle(req({action:'list',search:'x'.repeat(17000)}))).status,413);equal((await f.handle(req({action:'maintenance'},'invalid'))).status,401)});
Deno.test('retention deletes real objects through API before verifying metadata; failure leaves retryable state',async()=>{
 const f=fixture();let fail=false;f.service.rpc=(async(name:string,args:Record<string,unknown>)=>{f.calls.push({name,args});return{data:args.p_action==='candidates'?{rows:[{id:session,paths:['server/a.webm','server/b.webm']}]}:{ok:true},error:null}}) as unknown as Service['rpc'];
 f.service.storage.from=(()=>({async remove(paths:unknown){f.removed.push(paths);if(f.calls.at(-1)?.args.p_action==='deleted')throw new Error('wrong order');return{error:fail?'storage offline':null}}})) as unknown as Service['storage']['from'];
 equal((await cleanup(f.service)).deleted,1);equal(f.calls.at(-1)?.args.p_action,'deleted');fail=true;f.calls.length=0;let rejected=false;try{await cleanup(f.service)}catch{rejected=true}equal(rejected,true);equal(f.calls.some(c=>c.args.p_action==='deleted'),false);
});
